Repository eu-digital-identity-wallet/eudi-lib-kmp-statium, pull requests merged in 2025-04, with the labels that each got.

#7 Remove JVM-specific code from common
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/Platform.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/Types.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/GetStatusTest.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/misc/ByteArrayAsBase64UrlNoPaddingSerializerTest.kt
  lib/src/jvmAndAndroidMain/kotlin/eu/europa/ec/eudi/statium/Platform.jvmAndAndroid.kt
Labels: imrprovement

#8 Check status read is representable
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/ReadStatus.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/StatusTest.kt
Labels: imrprovement

#11 Remove from StatusList JSON-specific serialization logic
  gradle/libs.versions.toml
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/Types.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/misc/Base64UrlNoPaddingSerializer.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/misc/Decompress.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/misc/JsonSupport.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/ReadStatusTestVectors.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/StatusListTokenClaimsTest.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/misc/ByteArrayAsBase64UrlNoPaddingSerializerTest.kt
  lib/src/jvmAndAndroidMain/kotlin/eu/europa/ec/eudi/statium/misc/JvmAndroidDecompress.kt
Labels: imrprovement

#14 Remove JVM-specific StatusListTokenClaims
  lib/build.gradle.kts
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/Types.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/jose/Jwt.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/misc/DurationAsSecondsSerializer.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/misc/EpocSecondsSerializer.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/misc/StatiumJson.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/ReadStatusTestVectors.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/StatusListTokenClaimsTest.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/misc/ByteArrayAsBase64UrlNoPaddingSerializerTest.kt
Labels: imrprovement

#10 Switch to SonarCloud Github Action
  .github/workflows/sonar.yml
  gradle.properties
  gradle/libs.versions.toml
  lib/build.gradle.kts
Labels: enhancement

#16 Improve Sonar action
  .github/workflows/sonar.yml
Labels: enhancement

#17 Better align Sonar action with sast_bt
  .github/workflows/sonar.yml
Labels: enhancement

#20 Use gradle 8.8
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies, imrprovement

#18 Public API improvements
  gradle.properties
  lib/build.gradle.kts
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/GetStatus.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/ReadStatus.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/TokenStatusListSpec.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/Types.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/misc/BitsPerStatusSerializer.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/misc/DurationAsSecondsSerializer.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/misc/EpocSecondsSerializer.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/misc/StatiumJson.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/PositiveDurationAsSecondsTest.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/ReadStatusTest.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/ReadStatusTestVectors.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/StatusListTokenClaimsTest.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/StatusListTokenValidationsTest.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/StatusTest.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/misc/BitsPerStatusSerializerTest.kt
Labels: documentation, imrprovement

#21 Public API improvements (#18)
  gradle.properties
  lib/build.gradle.kts
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/GetStatus.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/ReadStatus.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/TokenStatusListSpec.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/Types.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/misc/BitsPerStatusSerializer.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/misc/DurationAsSecondsSerializer.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/misc/EpocSecondsSerializer.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/misc/StatiumJson.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/PositiveDurationAsSecondsTest.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/ReadStatusTest.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/ReadStatusTestVectors.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/StatusListTokenClaimsTest.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/StatusListTokenValidationsTest.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/StatusTest.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/misc/BitsPerStatusSerializerTest.kt
Labels: imrprovement

#22 Introduce allowed clock skew to status list token validations
  README.md
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/GetStatusListToken.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/StatusListTokenValidations.kt
  lib/src/commonMain/kotlin/eu/europa/ec/eudi/statium/Types.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/GetStatusTest.kt
  lib/src/commonTest/kotlin/eu/europa/ec/eudi/statium/StatusListTokenValidationsTest.kt
Labels: feature
